Naomi#2/create product models and controllers
Amaris-Digital/shoes-ecommerce pull request #14
Opened 2023-04-19 09:18 UTC by naomirono

This pull request includes several changes to add functionality to the product management system.

- `rails g resource Product name:string description:string price:string image:string`: Adds a Product model and migration to track products in the database.
- `rails db:migrate`: Updates the database schema with new fields for the Product model.
- product-serialiser.rb: Added attributes and validations to the Product_serializer.rb for use in JSON responses.
- products_controller.rb: Added `index`, `show`, `create`, `update`, and `destroy` methods to allow clients to interact with the API and perform CRUD operations on products.

Closes #2

2023-04-20 11:33 UTC, otsembo requested changes
Good job on the PR @naomirono 
Make the minor fix in the comments.

2023-04-20 11:33 UTC, otsembo commented on api/app/controllers/products_controller.rb
> +        @product = Product.find(params[:id])
You can add a rescue_from block in case `ActiveRecord` does not find a given product to avoid the server crashing in case the id provided is not valid.

2023-04-22 08:59 UTC, naomirono commented on api/app/controllers/products_controller.rb
> +        @product = Product.find(params[:id])
Thanks for your feedback. I have added a rescue_from block as suggested.

2023-04-22 13:23 UTC, otsembo approved these changes
Great job on the PR

2023-04-22 13:23 UTC, merged